name: Update sbot.m3u

on:
  schedule:
    - cron: "0 3 * * *"   # Her gün 03:00 UTC (Türkiye saatiyle 06:00)
  workflow_dispatch:       # İstersen manuel çalıştırabilirsin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: |
          pip install requests

      - name: SBOT'u çalıştır
        run: |
          python sbot.py

      - name: Güncel sbot.m3u dosyasını commit et
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git add sbot.m3u || true
         git diff --cached --quiet || git commit -m "Auto update sbot.m3u"
         git push || echo "Nothing to push"
 
